# Generated by Django 6.0.1 on 2026-01-13 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название подборки')),
                ('description', models.TextField(blank=True, verbose_name='Описание подборки')),
                ('is_public', models.BooleanField(default=True, help_text='Если отмечено, подборка будет видна всем пользователям', verbose_name='Публичная подборка')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('movies', models.ManyToManyField(blank=True, related_name='collections', to='movies.movie', verbose_name='Фильмы')),
            ],
            options={
                'verbose_name': 'Подборка фильмов',
                'verbose_name_plural': 'Подборки фильмов',
                'ordering': ['-created_at'],
            },
        ),
    ]
